import logging
import asyncio
from google import genai
from google.genai import types
from config import GEMINI_KEY

logger = logging.getLogger(__name__)

# ФИКС: Инициализируем клиент только если строка ключа НЕ пустая
if GEMINI_KEY and GEMINI_KEY.strip():
    client = genai.Client(api_key=GEMINI_KEY)
    logger.info("Gemini API client initialized successfully.")
else:
    client = None
    logger.warning("GEMINI_KEY is empty! AI replies will be disabled.")


async def generate_ai_reply(user_text: str) -> str:
    # Если ключ не был передан, ИИ просто молчит, и управление переходит к БД
    if not client:
        logger.warning("Gemini client is not initialized. Skipping AI generation.")
        return ""
        
    try:
        response = await asyncio.to_thread(
            client.models.generate_content,
            model='gemini-2.5-flash',
            contents=user_text,
            config=types.GenerateContentConfig(
                system_instruction="Ты — ИИ-ассистент...",
                max_output_tokens=300,
                temperature=0.7,
            )
        )
        return response.text
    except Exception as e:
        logger.error(f"Error generated by Gemini API: {e}")
        return ""
